spring:
  web:
    cors:
      mappings:
        "/api/**":
          allowed-origins: "https://aibeni9111.github.io"
          allowed-methods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
          allowed-headers: "*"
          # allow-credentials: true
