spring:
  mvc:
    cors:
      mappings:
        "[/**]":
          allowed-origin-patterns:
            - "http://localhost:5173"
            - "https://aibeni9111.github.io"
            - "https://*.github.io"
          allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
          allowed-headers: "*"
          allow-credentials: true
